### ISSUE TITLE
Cannot build on Ubuntu 20.04 using instructions on README

### ISSUE THREAD

**Issue by tylergale** [tuxedocomputers/tuxedo-control-center#6]
I have followed the instructions on a brand spanking new install of Ubuntu 20.04 and all pre-requisites have installed without issue.  I can do a "npm install" which completes just fine, but doing the "npm run  build" results in an error.  The terminal spits out the following:

```
> tuxedo-control-center@1.0.1 build /home/tyler/tuxedo-control-center
> run-s clean build-electron build-service build-native build-ng copy-files


> tuxedo-control-center@1.0.1 clean /home/tyler/tuxedo-control-center
> rm -rf ./dist; rm -rf ./build


> tuxedo-control-center@1.0.1 build-electron /home/tyler/tuxedo-control-center
> tsc -p ./src/e-app


> tuxedo-control-center@1.0.1 build-service /home/tyler/tuxedo-control-center
> tsc -p ./src/service-app && cp ./src/package.json ./dist/tuxedo-control-center/service-app/package.json && run-s bundle-service


> tuxedo-control-center@1.0.1 bundle-service /home/tyler/tuxedo-control-center
> pkg --target node10-linux-x64 --output ./dist/tuxedo-control-center/data/service/tccd ./dist/tuxedo-control-center/service-app/package.json

> pkg@4.4.7
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v10.17.0-linux-x64   [====================] 100%
> Warning Cannot find module 'TuxedoWMIAPI' from '/home/tyler/tuxedo-control-center/dist/tuxedo-control-center/service-app/native-lib'
  %1: /home/tyler/tuxedo-control-center/dist/tuxedo-control-center/service-app/native-lib/TuxedoWMIAPI.js

> tuxedo-control-center@1.0.1 build-native /home/tyler/tuxedo-control-center
> node-gyp configure && node-gyp rebuild

make: Entering directory '/home/tyler/tuxedo-control-center/build'
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/src/nothing.o
  AR(target) Release/obj.target/node_modules/node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/TuxedoECAPI/src/native-lib/tuxedo_ec_napi.o
  SOLINK_MODULE(target) Release/obj.target/TuxedoECAPI.node
  COPY Release/TuxedoECAPI.node
  CXX(target) Release/obj.target/TuxedoWMIAPI/src/native-lib/tuxedo_wmi_napi.o
  SOLINK_MODULE(target) Release/obj.target/TuxedoWMIAPI.node
  COPY Release/TuxedoWMIAPI.node
make: Leaving directory '/home/tyler/tuxedo-control-center/build'

> tuxedo-control-center@1.0.1 build-ng /home/tyler/tuxedo-control-center
> npm run copy-changelog && ng build


> tuxedo-control-center@1.0.1 copy-changelog /home/tyler/tuxedo-control-center
> cp CHANGELOG.md ./src/ng-app/assets/

Job name "..getProjectMetadata" does not exist.
Error: Job name "..getProjectMetadata" does not exist.
    at Observable._subscribe (/home/tyler/tuxedo-control-center/node_modules/@angular-devkit/core/src/experimental/jobs/simple-scheduler.js:350:23)
    at Observable._trySubscribe (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/Observable.js:30:22)
    at /home/tyler/tuxedo-control-center/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/operators/switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /home/tyler/tuxedo-control-center/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/operators/switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (/home/tyler/tuxedo-control-center/node_modules/rxjs/internal/Subscriber.js:66:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tuxedo-control-center@1.0.1 build-ng: `npm run copy-changelog && ng build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tuxedo-control-center@1.0.1 build-ng script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tyler/.npm/_logs/2020-04-22T01_25_16_367Z-debug.log
ERROR: "build-ng" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tuxedo-control-center@1.0.1 build: `run-s clean build-electron build-service build-native build-ng copy-files`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tuxedo-control-center@1.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tyler/.npm/_logs/2020-04-22T01_25_16_377Z-debug.log
```
### The contents of the error log is as follows:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle tuxedo-control-center@1.0.1~prebuild: tuxedo-control-center@1.0.1
6 info lifecycle tuxedo-control-center@1.0.1~build: tuxedo-control-center@1.0.1
7 verbose lifecycle tuxedo-control-center@1.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle tuxedo-control-center@1.0.1~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/tyler/tuxedo-control-center/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle tuxedo-control-center@1.0.1~build: CWD: /home/tyler/tuxedo-control-center
10 silly lifecycle tuxedo-control-center@1.0.1~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'run-s clean build-electron build-service build-native build-ng copy-files'
10 silly lifecycle ]
11 silly lifecycle tuxedo-control-center@1.0.1~build: Returned: code: 1  signal: null
12 info lifecycle tuxedo-control-center@1.0.1~build: Failed to exec build script
13 verbose stack Error: tuxedo-control-center@1.0.1 build: `run-s clean build-electron build-service build-native build-ng copy-files`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid tuxedo-control-center@1.0.1
15 verbose cwd /home/tyler/tuxedo-control-center
16 verbose Linux 5.4.0-25-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error tuxedo-control-center@1.0.1 build: `run-s clean build-electron build-service build-native build-ng copy-files`
22 error Exit status 1
23 error Failed at the tuxedo-control-center@1.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by girone** [comment]
I can confirm. The same happens on Ubuntu 16.04.

**Comment by vinzv** [comment]
Hey there, thanks for reporting the issue!

Have you tried to use the packaged version from our repository? There are brief steps explained how to add it [over here](https://www.tuxedocomputers.com/en/Infos/Help-and-Support/Instructions/Add-TUXEDO-Computers-software-package-sources.tuxedo#).

**Comment by girone** [comment]
At least for ubuntu 16.04 LTS no package exists. That's why I tried to build from source in the first place.

    $ sudo apt install tuxedo
    tuxedofancontrol         tuxedo-plymouth-one      tuxedo-wmi-dkms
    tuxedo-gtk-theme-one     tuxedo-sound-kernel-fix  
    tuxedo-icons-theme-one   tuxedo-wallpapers

**Comment by tosts** [comment]
I ran into the same problem after a npm audit fix.
According to angular/angular-cli#16902 that has to do, with an angular v9 vs v8 mismatch.
After updating to
```
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.24",
```
and an `npm install` my `npm run build` did succeed.

**Comment by steadfasterX** [comment]
> I ran into the same problem after a `npm audit fix`.
> According to [angular/angular-cli#16902](https://github.com/angular/angular-cli/issues/16902) that has to do, with an angular v9 vs v8 mismatch.
> After updating the package.json to
> 
> ```
>   "devDependencies": {
>     "@angular-devkit/build-angular": "~0.803.24",
> ```
> 
> and an `npm install` my `npm run build` did succeed.

great stuff! that worked for me as well (Manjaro Linux). 
after that I run into https://github.com/tuxedocomputers/tuxedo-control-center/issues/7 now though.

**Comment by tuxedoxt** [comment]
> I ran into the same problem after a `npm audit fix`.
> According to [angular/angular-cli#16902](https://github.com/angular/angular-cli/issues/16902) that has to do, with an angular v9 vs v8 mismatch.
> After updating the package.json to
> 
> ```
>   "devDependencies": {
>     "@angular-devkit/build-angular": "~0.803.24",
> ```
> 
> and an `npm install` my `npm run build` did succeed.

`npm audit fix` is a little bit too library breaking for my taste. For smooth use (and many other advantages) I would like to "port" to angular 9 eventually. However for the moment better stay with v8.

Question is if the problem appears on a clean repo clone. Anyone?

**Comment by steadfasterX** [comment]
> Question is if the problem appears on a clean repo clone. Anyone?

no. then it does not happen (at least here)

**Comment by girone** [comment]
> Have you tried to use the packaged version from our repository? There are brief steps explained how to add it over here.

@vinzv it seems that the package has not been released for xenial yet. Last update is from May 2019: http://deb.tuxedocomputers.com/ubuntu/dists/

Should I create a separate issue for that?

**Comment by vinzv** [comment]
> Should I create a separate issue for that?
Did that for you already. Package should be there quite soon.

**Comment by maravento** [comment]
please add to ubuntu repositories to install via apt. thks

**Comment by vinzv** [comment]
> > Question is if the problem appears on a clean repo clone. Anyone?
> 
> no. then it does not happen (at least here)

As this seems to be no problem (anymore) I'll close this issue. Feel free to reopen if necessary.
